apiVersion: v1
kind: Pod
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  containers:
  - name: sleep
    image: alpine:latest
    command: ["sleep", "10"]
  restartPolicy: Never
