apiVersion: v1
kind: Pod
metadata:
  name: during
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  containers:
  - name: sleep
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: Never
