apiVersion: v1
kind: Pod
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  containers:
  - name: sleep
    image: public.ecr.aws/z9p9f1p2/argocd-test:latest
    command: ["sleep", "10"]
#     command: ["/bin/sh"]
#     args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: Never
