apiVersion: v1
kind: Pod
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  containers:
  - name: sleep
    image: alpine:latest
    command: ["while :; do echo 'Hit CTRL+C'; sleep 1; done"]
  restartPolicy: Never
