apiVersion: v1
kind: Pod
metadata:
  name: chkk-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  containers:
  - name: sleep
    image: public.ecr.aws/z9p9f1p2/argocd-test:latest
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: APP_NAME
      value: {{ .Values.app }}
    command: ["/bin/sh", "-c"]
    args:
    - >
      git clone https://github.com/shahmirejaz/argocd-example-apps.git &&
      cd argocd-example-apps/pre-post-sync &&
      printenv
  restartPolicy: Never
