apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
  labels:
data:
  configManagementPlugins: |
    - name: test
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template . --post-renderer chkk-post-renderer-alpine"]
